### ISSUE TITLE
Request for 1.0.1 release

### ISSUE THREAD

**Issue by michalkucharczyk** [maciejhirsz/tiny-bip39#43]
What's the preferred process for incorporating the work in Pull Request #42  into the official release (1.0.1)? Should I initiate a Pull Request with a version bump?

**Comment by kayabaNerve** [comment]
I'd personally appreciate #45 and #46 be merged before a new release. #46 includes a major version bump to being an API break.

**Comment by maciejhirsz** [comment]
Closed with #51. #46 will have to wait and I make no promises I'll get to it, sorry.

Edit: #46 got included in the 2.0.0.

**Comment by DDtKey** [comment]
Please, pay attention to #52  🙏 
Thank you
